export interface GlossaryTerm {
  term: string
  category: string
  isOfficial: boolean
  description: string
  example: string
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    term: '対面',
    category: '盤面',
    isOfficial: false,
    description: '今、場に出ているポケモン同士の関係。目の前の1対1で勝てるかを考える時に使う。',
    example: '「この対面は素早さで勝っていて、弱点技も押せる」',
  },
  {
    term: 'サイクル',
    category: '構築',
    isOfficial: false,
    description: '交換を使って有利な対面を作り直し、少しずつ相手を削る考え方。',
    example: '「みず技を受けられるポケモンへ引いてサイクルを回す」',
  },
  {
    term: '積み',
    category: '勝ち筋',
    isOfficial: false,
    description: '能力を上げる技を使い、後のターンで一気に倒し切る準備をすること。',
    example: '「相手が交換しそうなターンにこうげきを積む」',
  },
  {
    term: '展開',
    category: '勝ち筋',
    isOfficial: false,
    description: '壁、天候、フィールド、素早さ操作などで、味方が動きやすい状態を作ること。',
    example: '「先発で壁を展開して、後続の積み技につなぐ」',
  },
  {
    term: '設置技',
    category: '補助技',
    isOfficial: false,
    description: '相手の場に残り、交代で出てきたポケモンにダメージや状態変化を与える技。',
    example: '「ステルスロックを置いて相手の交代先を削る」',
  },
  {
    term: 'ステロ',
    category: '補助技',
    isOfficial: false,
    description: 'ステルスロックの略。相手が場に出るたび、いわタイプ相性に応じて削る設置技。',
    example: '「ステロを撒いて、ひこうタイプを出しにくくする」',
  },
  {
    term: '定数ダメージ',
    category: '攻撃',
    isOfficial: false,
    description: '通常の攻撃計算ではなく、最大HPの割合など決まった形で入るダメージ。',
    example: '「まきびしとどくで定数ダメージを重ねる」',
  },
  {
    term: '努力値振り',
    category: '育成',
    isOfficial: false,
    description: 'どの能力を伸ばすかを決める育成配分。HABCDSの略称で書かれることが多い。',
    example: '「HD振りで特殊技を受けやすくする」',
  },
  {
    term: '努力値',
    category: '育成',
    isOfficial: false,
    description: '能力を伸ばすための育成要素。ゲーム内では基礎ポイントと呼ばれることがある。',
    example: '「Sに努力値を振って先に動けるようにする」',
  },
  {
    term: '実数値',
    category: '育成',
    isOfficial: false,
    description: 'バトルで実際に使われる能力値。種族値、努力値、性格補正、個体値などで決まる。',
    example: '「実数値で相手より1高いSに調整する」',
  },
  {
    term: '種族値',
    category: '育成',
    isOfficial: false,
    description: 'ポケモンごとに決まっている基礎能力。どの能力が高いかを見る時の目安。',
    example: '「S種族値が高いので上から動きやすい」',
  },
  {
    term: '性格補正',
    category: '育成',
    isOfficial: false,
    description: '性格によって能力が上がったり下がったりする補正。最速や火力補正の話でよく出る。',
    example: '「Sに性格補正をかけて最速にする」',
  },
  {
    term: '個体値',
    category: '育成',
    isOfficial: false,
    description: '個体ごとの能力差を表す育成要素。最遅調整では低くすることがある。',
    example: '「トリックルーム用にS個体値を低くする」',
  },
  {
    term: 'ぶっぱ',
    category: '育成',
    isOfficial: false,
    description: '特定の能力に努力値を最大近くまで振ること。ASぶっぱ、CSぶっぱのように使う。',
    example: '「CSぶっぱで上から特殊技を押す」',
  },
  {
    term: 'S調整',
    category: '育成',
    isOfficial: false,
    description: '特定の相手より先に動けるよう、すばやさへの努力値や性格を調整すること。',
    example: '「最速200抜きまでS調整する」',
  },
  {
    term: 'Sライン',
    category: '育成',
    isOfficial: false,
    description: 'すばやさの基準や境目。どの相手を抜くか考える時に使う。',
    example: '「この構築はSラインが低いので先制技を入れる」',
  },
  {
    term: '族',
    category: '育成',
    isOfficial: false,
    description: '同じくらいの種族値を持つポケモンをまとめて呼ぶ非公式表現。',
    example: '「S100族を基準に素早さを考える」',
  },
  {
    term: 'S130族',
    category: '育成',
    isOfficial: false,
    description: '素早さ種族値が130のポケモンたちを指す非公式表現。Lv50の最速目安は200で、全ポケモン中の最速という意味ではない。',
    example: '「最速200抜きまで素早さを調整する」',
  },
  {
    term: '最速',
    category: '育成',
    isOfficial: false,
    description: 'そのポケモンの素早さを大きく伸ばし、素早さが上がる性格にした状態。全ポケモン中で一番速いという意味ではない。',
    example: '「最速にして同族対決を意識する」',
  },
  {
    term: '最速実数値',
    category: '育成',
    isOfficial: false,
    description: '最速にした時の実際の素早さ。最速200、最速205のように、抜き調整の基準として使う。',
    example: '「最速205抜きには実数値206以上が必要」',
  },
  {
    term: '準速',
    category: '育成',
    isOfficial: false,
    description: '素早さに大きく振るが、素早さが上がる性格ではない状態。',
    example: '「準速で火力補正を残す」',
  },
  {
    term: 'トリックルーム',
    category: '素早さ',
    isOfficial: true,
    description: '一定ターン、同じ優先度の技の中で素早さが低いポケモンから動きやすくなる場の効果。本編作品では5ターンが基本で、優先度そのものは逆転しない。',
    example: '「トリックルーム下で遅い高火力アタッカーを通す」',
  },
  {
    term: '持ち物',
    category: '構築',
    isOfficial: true,
    description: 'ポケモンに1つ持たせる道具。火力、耐久、素早さ、行動保証など役割を補強する。',
    example: '「先発にきあいのタスキを持たせて行動保証を作る」',
  },
  {
    term: 'こだわり',
    category: '持ち物',
    isOfficial: false,
    description: 'こだわりハチマキ、こだわりメガネ、こだわりスカーフの総称。能力を伸ばす代わりに同じ技しか選べなくなる。',
    example: '「こだわりスカーフで上から攻撃する」',
  },
  {
    term: 'タスキ',
    category: '持ち物',
    isOfficial: false,
    description: 'きあいのタスキの略。HP満タンなら大きな攻撃を耐えて1回動きやすくする。',
    example: '「タスキで耐えてステルスロックを置く」',
  },
  {
    term: 'ポルターガイスト',
    category: '持ち物',
    isOfficial: true,
    description: '相手が持ち物を持っている時に成立するゴーストタイプの攻撃。相手が持ち物を持っていないと失敗する。',
    example: '「相手が持ち物を消費した後はポルターガイストを受けやすくなる」',
  },
  {
    term: 'はたきおとす',
    category: '持ち物',
    isOfficial: true,
    description: '相手の持ち物を落とす攻撃。持ち物を失うことで、耐久、素早さ、展開の計画が崩れることがある。',
    example: '「あつぞこブーツをはたきおとされて設置技が重くなる」',
  },
  {
    term: 'トリック',
    category: '持ち物',
    isOfficial: true,
    description: '自分と相手の持ち物を入れ替える技。こだわり系を押し付けて相手の動きを縛る使い方がある。',
    example: '「受けポケモンにこだわりメガネをトリックする」',
  },
  {
    term: 'マジックミラー',
    category: '特性',
    isOfficial: true,
    description: '一部の変化技を相手側へ跳ね返す特性。ステルスロックなどの設置技、ちょうはつ、状態異常技への対策になる。',
    example: '「マジックミラー持ちの前でステルスロックを押すと返されることがある」',
  },
  {
    term: 'おうごんのからだ',
    category: '特性',
    isOfficial: true,
    description: '他のポケモンから受ける多くの変化技を無効化する特性。反射ではなく無効化として考える。',
    example: '「おうごんのからだでちょうはつを受けにくい」',
  },
  {
    term: '受け',
    category: '役割',
    isOfficial: false,
    description: '相手の攻撃を耐えて、回復や状態異常、交換で試合を長く使う役割。',
    example: '「物理受けで相手のこうげき技を止める」',
  },
  {
    term: '受け出し',
    category: '交換',
    isOfficial: false,
    description: '相手の攻撃を予想して、耐えられるポケモンへ交代すること。',
    example: '「じめん技読みでひこうタイプへ受け出しする」',
  },
  {
    term: '引き先',
    category: '交換',
    isOfficial: false,
    description: '不利対面になった時に交代して出せるポケモン。',
    example: '「でんき技の引き先を構築に入れておく」',
  },
  {
    term: '一貫',
    category: '攻撃',
    isOfficial: false,
    description: '相手の複数体に同じタイプや技が通りやすい状態。',
    example: '「相手のパーティーにはこおり技が一貫している」',
  },
  {
    term: '起点',
    category: '勝ち筋',
    isOfficial: false,
    description: '相手がこちらを止めにくく、積み技や展開の準備に使いやすい相手やターン。',
    example: '「回復しかできない相手を起点にする」',
  },
  {
    term: '切る',
    category: '判断',
    isOfficial: false,
    description: '勝ち筋を残すため、あえて1体を倒される前提で動かすこと。',
    example: '「このポケモンを切って、安全にエースを出す」',
  },
  {
    term: '択',
    category: '判断',
    isOfficial: false,
    description: '複数の選択肢があり、相手の行動次第で正解が変わる場面。',
    example: '「攻撃するか交換するかの択になる」',
  },
  {
    term: '安定択',
    category: '判断',
    isOfficial: false,
    description: '最大リターンではなくても、外した時の損が小さい選択。',
    example: '「相手が居座っても交代しても悪くない技を押す」',
  },
  {
    term: '勝ち筋',
    category: '判断',
    isOfficial: false,
    description: 'ここから勝つために必要な手順。誰を残し、誰で倒し切るかまで含む。',
    example: '「最後は素早いエースを通す勝ち筋を残す」',
  },
  {
    term: '詰め筋',
    category: '判断',
    isOfficial: false,
    description: '終盤に相手の選択肢を減らし、勝ちへ近づける手順。',
    example: '「先制技圏内まで削って詰め筋を作る」',
  },
  {
    term: '行動保証',
    category: '役割',
    isOfficial: false,
    description: 'きあいのタスキ、耐久、特性などにより、最低1回は行動しやすい性質。',
    example: '「行動保証がある先発で場作りをする」',
  },
  {
    term: '縛り',
    category: '攻撃',
    isOfficial: false,
    description: '相手が次の攻撃で倒されるため、自由に動きにくい状態。',
    example: '「先制技で縛れているので、相手は交換しづらい」',
  },
  {
    term: '役割集中',
    category: '構築',
    isOfficial: false,
    description: '同じ受け先に負担を集め、どこかで崩す考え方。',
    example: '「2体の物理アタッカーで相手の物理受けに役割集中する」',
  },
]
